try ci

diff --git a/.github/workflows/ci-windows.yml b/.github/workflows/ci-windows.yml
--- a/.github/workflows/ci-windows.yml
+++ b/.github/workflows/ci-windows.yml
@@ -15,126 +15,44 @@ jobs:
     name: ${{ matrix.toolchain }} + ${{ matrix.cxx }} + ${{ matrix.arch }}
     runs-on: ${{ matrix.os }}
     steps:
-      - name: Upgrade LLVM
-        run: choco upgrade llvm
-        
       - name: Checkout code
         uses: nschloe/action-cached-lfs-checkout@v1
         
-      # many thanks to NazaraEngine: https://github.com/NazaraEngine/NazaraEngine
-      - name: Get current date as package key
-        id: cache_key
-        run: echo "key=$(date +'%W')" >> $GITHUB_OUTPUT
-        shell: bash
-
-      # Force xmake to a specific folder (for cache)
-      - name: Set xmake env
-        run: echo "XMAKE_GLOBALDIR=${{ runner.workspace }}/xmake-global" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
-
-      # install xmake
-      - uses: ilammy/msvc-dev-cmd@v1
-      - name: Install xmake
-        uses: xmake-io/github-action-setup-xmake@v1
-        with:
-          # xmake-version: latest
-          xmake-version: '2.9.2'
-          actions-cache-folder: .xmake-cache-W${{ steps.cache_key.outputs.key }}
-
-      # Update xmake repository (in order to have the file that will be cached)
-      - name: Update xmake repository
-        run: xmake repo --update
-
-      # Fetch xmake dephash
-      - name: Retrieve dependencies hash
-        id: dep_hash
-        run: echo "hash=$(xmake l utils.ci.packageskey)" | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
-
       # Cache xmake dependencies
-      - name: Retrieve cached xmake dependencies
+      - name: Retrieve cached package artifacts
         uses: actions/cache@v3
         with:
-          path: ${{ env.XMAKE_GLOBALDIR }}\.xmake\packages
-          key: Windows-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}-${{ steps.dep_hash.outputs.hash }}-W${{ steps.cache_key.outputs.key }}-15
+          path: |
+            .sb
+            .pkgs
+            .build
+          key: Windows-${{ matrix.arch }}-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}
 
-      - name: ConfigureDebug
-        run: |
-          cp ./.github/workflows/ci.project.lua ./project.lua  
-          xmake f -m debug --arch=${{ matrix.arch }} --toolchain=${{ matrix.toolchain }} --cxx_version=${{ matrix.cxx }} -c -y -v --policies=build.ccache:n
-      
-      - name: BuildDebug
+      - name: BuildTools
         if: success() || failure()
         shell: cmd
-        run: xmake -y -v
-      
-      - name: TestDebug
-        if: success()
-        env:
-          TRACY_NO_INVARIANT_CHECK: 1
-        run: |
-          xmake test -g 05.tests/* -vD ... -d yes
-      
-      - name: ConfigureRelease
-        if: success() || failure()
-        shell: cmd
-        run: |
-          cp ./.github/workflows/ci.project.lua ./project.lua  
-          xmake f -m release --arch=${{ matrix.arch }} --toolchain=${{ matrix.toolchain }} --cxx_version=${{ matrix.cxx }} -c -y -v --use_profile=disable --policies=build.ccache:n
-      
-      - name: BuildRelease
-        if: success() || failure()
-        shell: cmd
-        run: xmake -y -v
-      
-      - name: TestRelease
-        if: success()
-        env:
-          TRACY_NO_INVARIANT_CHECK: 1
-        run: |
-          xmake test -g 05.tests/* -vD ... -d yes
+        run: dotnet run SB tools
 
-      - name: UploadGeneratedFiles
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: build-artifacts-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}
-          path: build/.gens
-      
-      - name: UploadCompileResults
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: build-binaries-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}
-          path: build/windows
-      
-      - name: RemoveBuildDir
-        uses: JesseTG/rm@v1.0.3
-        with:
-          path: build/windows
-      
-      - name: CleanBuild
+      - name: BuildPrograms
         if: success() || failure()
         shell: cmd
-        run: |
-          xmake c -av
-
-      - name: Shipping
-        if: success() || failure()
-        shell: cmd
-        run: |
-          cp ./.github/workflows/ci.project.lua ./project.lua  
-          xmake f -c -y -m release --arch=${{ matrix.arch }} --toolchain=${{ matrix.toolchain }} --cxx_version=${{ matrix.cxx }} -c -y -v --shipping_one_archive=y --use_profile=disable --policies=build.ccache:n
-          xmake -y -v
+        run: dotnet run SB
       
-      - name: UploadGeneratedFiles2
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: shipping-artifacts-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}
-          path: build/.gens
+      # - name: TestDebug
+      #   if: success()
+      #   env:
+      #     TRACY_NO_INVARIANT_CHECK: 1
+      #   run: |
+      #     xmake test -g 05.tests/* -vD ... -d yes
       
-      - name: UploadShipping
-        if: success() || failure()
-        uses: actions/upload-artifact@v4
-        with:
-          name: shipping-binaries-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}
-          path: build/windows
+      # - name: UploadCompileResults
+      #   if: success() || failure()
+      #   uses: actions/upload-artifact@v4
+      #   with:
+      #     name: build-binaries-${{ matrix.os }}-${{ matrix.toolchain }}-${{ matrix.cxx }}
+      #     path: build/windows
+      
+      # - name: RemoveBuildDir
+      #   uses: JesseTG/rm@v1.0.3
+      #   with:
+      #     path: build/windows
